### ISSUE TITLE
I met some problem，please

### ISSUE THREAD

**Issue by qqqq1314** [albertgassol1/vf-nerf#1]
python train/vf_nerf_exp_runner.py --scene office0 --expname ex1  

FileNotFoundError: [Errno 2] No such file or directory: 'data\\Replica\\office0\\office0.pth'

**Comment by albertgassol1** [comment]
Hi, thanks for pointing this out. I updated the readme with instructions to solve this. Please see https://github.com/albertgassol1/vf-nerf/blob/main/README.md#data

**Comment by qqqq1314** [comment]
Hello, I have a question to ask you. Why can't I increase the GPU usage of this code。and I have not the tinycudnn,maybe it is the reason？and tinycudann site in the requirements can not use



---Original---
From: "Albert ***@***.***&gt;
Date: Wed, Sep 11, 2024 17:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [albertgassol1/vf-nerf] I met some problem，please (Issue #1)




 
Closed #1 as completed.

**Comment by qqqq1314** [comment]
My gpu usage have only 6GB

---Original---
From: "Albert ***@***.***&gt;
Date: Wed, Sep 11, 2024 17:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [albertgassol1/vf-nerf] I met some problem，please (Issue #1)




 
Closed #1 as completed.

**Comment by albertgassol1** [comment]
Hey, tinycuda is not needed. I actually removed it, it was used in some old experiments;) What do you mean by increasing the GPU usage?
1. Increasing batch size/samples? That should be doable?
2. Reduce the GPU usage, so basically using less GPU memory?

**Comment by qqqq1314** [comment]
What I mean is, after the code starts running. The CPU usage rate has increased, but the GPU usage rate has not increased, only the GPU's graphics memory occupies 6 GB. My device is 4090, and it prompts me to run for 65 hours



---Original---
From: "Albert ***@***.***&gt;
Date: Mon, Sep 30, 2024 15:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [albertgassol1/vf-nerf] I met some problem，please (Issue #1)




 
Hey, tinycuda is not needed. I actually removed it, it was used in some old experiments;) What do you mean by increasing the GPU usage?
  
Increasing batch size/samples? That should be doable?
 
Reduce the GPU usage, so basically using less GPU memory?

**Comment by qqqq1314** [comment]
In running the code, I saw a dataloader with a batch size of 1, but increasing the batch size would result in an error



---Original---
From: "Albert ***@***.***&gt;
Date: Mon, Sep 30, 2024 15:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [albertgassol1/vf-nerf] I met some problem，please (Issue #1)




 
Hey, tinycuda is not needed. I actually removed it, it was used in some old experiments;) What do you mean by increasing the GPU usage?
  
Increasing batch size/samples? That should be doable?
 
Reduce the GPU usage, so basically using less GPU memory?

**Comment by albertgassol1** [comment]
You can increase the 'pixels_per_batch' and 'rays_per_batch' and 'rays_per_batch'. You can then reduce the number of epochs if you'd like. 
I do not understand why your GPU rate doesn't increase though. Typically, with the default parameters the GPU memory usage should be around 10-12GB if I remember correctly

**Comment by qqqq1314** [comment]
I am using the Office 0 dataset. May I ask in which file are the pixels_per_match 'and' rays_per_match 'and' rays_per_match 'that you mentioned。



---Original---
From: "Albert ***@***.***&gt;
Date: Mon, Sep 30, 2024 15:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [albertgassol1/vf-nerf] I met some problem，please (Issue #1)




 
You can increase the 'pixels_per_batch' and 'rays_per_batch' and 'rays_per_batch'. You can then reduce the number of epochs if you'd like.
 I do not understand why your GPU rate doesn't increase though. Typically, with the default parameters the GPU memory usage should be around 10-12GB if I remember correctly

**Comment by albertgassol1** [comment]
Yes, it is in the confs/vf_nerf.conf (https://github.com/albertgassol1/vf-nerf/blob/f352686021c79ac5d02f9e2f78fc13d2408abd5e/confs/vf_nerf.conf#L98)

**Comment by qqqq1314** [comment]
Why are norm_stmaller_than_one-loss and direction_derivatives always 0




---Original---
From: "Albert ***@***.***&gt;
Date: Mon, Sep 30, 2024 15:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [albertgassol1/vf-nerf] I met some problem，please (Issue #1)




 
Yes, it is in the confs/vf_nerf.conf (https://github.com/albertgassol1/vf-nerf/blob/f352686021c79ac5d02f9e2f78fc13d2408abd5e/confs/vf_nerf.conf#L98)

**Comment by qqqq1314** [comment]
I have increased the ray_perypatch, although the GPU usage has increased, the training speed has not changed



---Original---
From: "Albert ***@***.***&gt;
Date: Mon, Sep 30, 2024 15:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [albertgassol1/vf-nerf] I met some problem，please (Issue #1)




 
You can increase the 'pixels_per_batch' and 'rays_per_batch' and 'rays_per_batch'. You can then reduce the number of epochs if you'd like.
 I do not understand why your GPU rate doesn't increase though. Typically, with the default parameters the GPU memory usage should be around 10-12GB if I remember correctly

**Comment by albertgassol1** [comment]
> Why are norm_stmaller_than_one-loss and direction_derivatives always 0


These were used in some old experiments but they didn't bring any value

> I have increased the ray_perypatch, although the GPU usage has increased, the training speed has not changed

Increasing the pixels_per_batch or 'rays_per_batch' will not increase the training speed. This is because each epoch still loops over the number of images in the dataset because it is fixed. However, if you increase these parameters you can reduce the number of epochs and it will train faster of course:)

**Comment by qqqq1314** [comment]
The network has the same parameter configuration, and it takes me 55 hours to run on a computer with 4060GPU and i9-14900CPU. It takes 65 hours to run on 4090GPU and i9-12700CPU. I think the training speed of this project should be related to the CPU




---Original---
From: "Albert ***@***.***&gt;
Date: Mon, Sep 30, 2024 19:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [albertgassol1/vf-nerf] I met some problem，please (Issue #1)




  
Why are norm_stmaller_than_one-loss and direction_derivatives always 0
 These were used in some old experiments but they didn't bring any value
   
I have increased the ray_perypatch, although the GPU usage has increased, the training speed has not changed
 Increasing the pixels_per_batch or 'rays_per_batch' will not increase the training speed. This is because each epoch still loops over the number of images in the dataset because it is fixed. However, if you increase these parameters you can reduce the number of epochs and it will train faster of course:)

**Comment by albertgassol1** [comment]
There are parts of the code (dataloader, ray sampling, and some orher computation) that are run on cpu. You can move it to GPU if you have enough memory and it might be faster although I doubt it. The code has not been optimized for speed so there might be parts that can be much more optimized. Anyways reducing the epochs and increasing the number of pixels per batch will still give you the most increase in training time without having to go through too much trouble!

**Comment by qqqq1314** [comment]
How can I modify the code if I want to run all the parts on the GPU？


---Original---
From: "Albert ***@***.***&gt;
Date: Tue, Oct 1, 2024 02:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [albertgassol1/vf-nerf] I met some problem，please (Issue #1)




 
There are parts of the code (dataloader, ray sampling, and some orher computation) that are run on cpu. You can move it to GPU if you have enough memory and it might be faster although I doubt it. The code has not been optimized for speed so there might be parts that can be much more optimized. Anyways reducing the epochs and increasing the number of pixels per batch will still give you the most increase in training time without having to go through too much trouble!

**Comment by qqqq1314** [comment]
Hello, may I ask how I need to visualize this code after running it. Is the log file generated in Wandb used




---Original---
From: "Albert ***@***.***&gt;
Date: Tue, Oct 1, 2024 02:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [albertgassol1/vf-nerf] I met some problem，please (Issue #1)




 
There are parts of the code (dataloader, ray sampling, and some orher computation) that are run on cpu. You can move it to GPU if you have enough memory and it might be faster although I doubt it. The code has not been optimized for speed so there might be parts that can be much more optimized. Anyways reducing the epochs and increasing the number of pixels per batch will still give you the most increase in training time without having to go through too much trouble!

**Comment by albertgassol1** [comment]
> How can I modify the code if I want to run all the parts on the GPU？

You will have to move the ray sampling and other computation to GPU. I can't recall exactly which parts are on CPU but you can easily check whatever is not moved to(device).

> Hello, may I ask how I need to visualize this code after running it. Is the log file generated in Wandb used

If you want to visualize meshes or rendered views you can follow the Evaluation section of the README. If you want to visualize losses you can use wandb
